services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus-monitor
    volumes:
      - /data/coolify/applications/tkog00kogs0wgo0g8sc4so0w/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always